### ISSUE TITLE
Any support for bluetooth operations?

### ISSUE THREAD

**Issue by wgehalo** [switchbrew/libnx#152]
Hey there,
I was looking around and can't find anything related to the bluetooth stack. Is it possible to support bluetooth operations at this layer?

I'm guessing if it was it would probably be in here already, but I figured I'd at least ask about it. I'd love to develop a way to allow wii u pro controllers to pair with the switch bluetooth controller.

**Comment by yellows8** [comment]
It would need documented first.

" allow wii u pro controllers to pair with the switch bluetooth controller." Don't know how this could be done without complicated hid-sysmodule modifying...

**Comment by wgehalo** [comment]
Hey thanks for the response!

I talked a bit about this on the reswitched discord and yeah, it's definitely more involved than I originally imagined, not as simple as just getting the bluetooth controller to pair with the wii u stuff.

I'm going to learn more about developing homebrew on the switch before coming back to this.

**Comment by yellows8** [comment]
So FWIW regarding the HID side: the closest thing to this with official service-cmds requires the app reading controller state to use special cmds. Can't do it with normal HID usage, which official games would require. It could be done with homebrew apps which support said special cmds, but *only if* it allows setting state from a different process (not tested).

Don't think the auto-pilot cmds apply to this use-case. Xpad probably doesn't apply either since {special cmds}.

Still haven't really checked the Bluetooth side.

**Comment by yellows8** [comment]
https://github.com/switchbrew/libnx/issues/210#issuecomment-499721698
