### ISSUE TITLE
APP_TITLEID is ignored in Makefile

### ISSUE THREAD

**Issue by SwitchMods** [switchbrew/libnx#195]
The APP_TITLEID tag is ignored in makefile (libnx 1.5.0 in devkitPro). Instead of putting the specified tittleid in the nacp file, there is still the standard (00000000ffffffff) titleid.

This is how I specified my titleid in makefile:
`APP_TITLEID = 0100000000000002`

FIY: APP_TITLE, APP_AUTHOR and APP_VERSION are working correctly.

**Comment by SwitchMods** [comment]
> May I ask, why do you need to change the title id?

Sure you can ask, but there is no real answer to this question :P I'm just trying to make a game (using SDL) and wanted to give it a custom title id. Since I figured out that it was not working as expected, I decided to report a bug, maybe someone will be able to fix this for others :)

**Comment by fincs** [comment]
Why does your SDL game need a custom title id? Keep in mind that homebrew gets distributed as .nro files, which are launched through nx-hbloader.

**Comment by SwitchMods** [comment]
> Why does your SDL game need a custom title id? Keep in mind that homebrew gets distributed as .nro files, which are launched through nx-hbloader.

I know I know, as I said, I just found a bug (something that is supposed to work is not working) and I'm reporting this. I can hex-patching my nacp file without problem, but this not the point here. I don't understand this hostility.

**Comment by fincs** [comment]
I'm just trying to understand your situation, not meant to be hostile. May I ask, what are you doing exactly to build the game? It sounds to me like there's something off in your build system.

**Comment by SwitchMods** [comment]
> I'm just trying to understand your situation, not meant to be hostile. May I ask, what are you doing exactly to build the game? It sounds to me like there's something off in your build system.

No offence, and now offence taken :) I was just trying to help reposting bugs ;)
I'm using devkitPro (with latest libnx version: 1.5.0). Just can just replicate this bug on your side by compiling a simple hello work and adding this to your makefile:

```
APP_TITLE	=	YourAppTitle
APP_AUTHOR	=	YourName
APP_VERSION	=	1
APP_TITLEID =	0100000000000002
```
just after

```
TARGET		:=	$(notdir $(CURDIR))
BUILD		:=	build
SOURCES		:=	source
DATA		:=	data
INCLUDES	:=	include
EXEFS_SRC	:=	exefs_src
#ROMFS	:=	romfs 

```


Just let me know if it is working for you (if yes, then I'm very sorry and the problem is elsewhere)

**Comment by fincs** [comment]
I see. You should not build homebrew in "XCI" format, because "XCI" files are dangerous, they can get people's consoles banned (detected by Nintendo), they need third party tools of questionable legality to build, they need signature checks to install and overall, seem to be promoted by people who participate in warez/piracy.

Homebrew is normally built and distributed in .nro format, which can be loaded using nx-hbloader and nx-hbmenu. This is much safer, plays nicely with the system, doesn't require signature check patches, and is supported natively by Atmosphère. Also, the latest version of hbloader allows you to access the same memory resources (~3.2GB) that official applications are able to peruse, so there is no disadvantage compared to "XCI".

I'm sorry to be the one to tell you this, but if you have been told to build homebrew in "XCI" format, let me warn you that you have been heavily misinformed, and none of what they have told you to do is the recommended/legitimate way to develop and run homebrew.

If you need more information and clarification, we're more than happy to assist you. We can be reached on IRC, we idle on #switchdev @ EFnet.
