### ISSUE TITLE
Multimedia Player App Tri-player cannot be compiled to work in 12.0.0 due to an SDL not properly updated to 4.0.0 HID Changes

### ISSUE THREAD

**Issue by TheSniperFox** [switchbrew/libnx#544]
Hello, i just contacted tallbl0nde regarding to a problem when he tried to compile the multimedia app using this that crashes when in use to the 12.0.0 update. 

He mentioned that something about this libnx build. And i want to know the status or whats going on now with it. 

"Little update: I tried compiling with the very latest libnx commits and while the sysmodule compiles, the application doesn't. It uses SDL which hasn't been updated properly for the 4.0.0 HID changes, which seem to be removed entirely in libnx for the next version. Looks like we'll have to wait for them to properly update all the libraries, so 12.0.0 won't be supported for a little while."

**Comment by fincs** [comment]
This is what happens when unreleased development versions of libnx are used to compile projects, and conclusions are reached without asking first. While it is true that the `master` branch has the old HID API removed, it doesn't imply that the next release will contain this removal. We are still working on completing 12.x support in libnx, the packages will be released in due time. You can be assured that SDL compatibility won't be broken by any libnx release we do.
