### ISSUE TITLE
Rotated/Normalized controller layouts using the pad abstraction API

### ISSUE THREAD

**Issue by p-sam** [switchbrew/libnx#565]
Hi,

I'm looking to replicate a behavior that was present using the deprecated HID API now with the pad*() abstraction API, specifically how buttons were read when HidControllerLayoutType was set to `LAYOUT_DEFAULT`. The old docs describes it better than I would: 

```
Safe default. Single-mode and ::HidJoyHoldType_Horizontal: Joy-Con have buttons/sticks rotated for orientation,
where physical Z(L/R) are unavailable and S(L/R) are mapped to L/R (with physical L/R unavailable).
```

Using the example [available here](https://github.com/switchbrew/switch-examples/blob/master/hid/read-controls/source/main.c) as a base, and adding `hidSetNpadJoyHoldType(HidNpadJoyHoldType_Horizontal);` before anything else, a left joycon as controller 1 will give dpad inputs instead of button inputs, left instead of down, etc. 

Did I miss the new API counterpart for that behavior, or is it a design choice to leave it out? libnx didn't seem to be responsible for the conversion itself, and I don't know right know if such behavior can be achieved without a libnx version rollback.

Thanks

**Comment by fincs** [comment]
The old libnx hid api was using a controller style type by default that, as far as we're able to tell, is internally reserved for use by the Switch's native UI (home menu, overlay applets, etc), presumably to simplify the handling of various different controllers across the codebase. In fact, Nintendo made a breaking change in the handling of this internal style type in an older system version that caused libnx to need a fix and all homebrew to need recompiling; otherwise they'd fail to receive any input whatsoever.

In the new hid api, we decided to closely follow what Nintendo offers to game developers in order to avoid future breakage and pain. As far as we can tell, there is no way to get automatic horizontal layout translation, and games are expected to handle this on their own.

**Comment by p-sam** [comment]
Should I make a related issue on the SDL repo then? I presume all SDL ports made until now lost split joycon support by updating their deps, unless I missed something

**Comment by vrince** [comment]
I know this is a close issue and I get your point (horizontal layout will be taken care of on "game side"). But is there a way to know controller have been set in horizontal mode from the switch ? I mean I get the controller Id correctly (both left ant right joycon get a different id) but I do not find a way to know that they are in separated mode. Any hint ?
